### ISSUE TITLE
numpy 版本引起 TypeError

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/stagesepx#101]
```text
Traceback (most recent call last):
  File "classify_with_model.py", line 25, in <module>
    classify_result = cl.classify(video, stable, keep_data=True)
  File "/usr/local/lib/python3.7/site-packages/stagesepx/classifier/base.py", line 359, in classify
    result = self._classify_frame(frame, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/stagesepx/classifier/keras.py", line 198, in _classify_frame
    return self.predict_with_object(frame.data)
  File "/usr/local/lib/python3.7/site-packages/stagesepx/classifier/keras.py", line 193, in predict_with_object
    frame = np.expand_dims(frame, axis=[0, -1])
  File "<__array_function__ internals>", line 6, in expand_dims
  File "/Users/aa/Library/Python/3.7/lib/python/site-packages/numpy/lib/shape_base.py", line 577, in expand_dims
    if axis > a.ndim or axis < -a.ndim - 1:
TypeError: '>' not supported between instances of 'list' and 'int'
```

1.17.4 有问题
1.18.1 无问题

**Comment by williamfzc** [comment]
https://github.com/numpy/numpy/pull/14051
