### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by IcyW** [williamfzc/stagesepx#103]
运行example/cut_and_classify.py报错：

```python
Traceback (most recent call last):
  File "example/cut_and_classify.py", line 154, in <module>
    prune=None,
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/cutter/cut_result.py", line 370, in pick_and_save
    compressed = toolbox.compress_frame(each_frame_object.data, **kwargs)
AttributeError: 'NoneType' object has no attribute 'data'
```
填写了prune参数后：
```python
Traceback (most recent call last):
  File "example/cut_and_classify.py", line 154, in <module>
    prune=0.9,
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/cutter/cut_result.py", line 333, in pick_and_save
    stage_list = self._prune(prune, stage_list)
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/cutter/cut_result.py", line 391, in _prune
    ssim_list = toolbox.multi_compare_ssim(frames, next_frames)
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/toolbox.py", line 62, in multi_compare_ssim
    return [compare_ssim(a, b) for a, b in zip(pic1_list, pic2_list)]
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/toolbox.py", line 62, in <listcomp>
    return [compare_ssim(a, b) for a, b in zip(pic1_list, pic2_list)]
  File "/Users/xxxx/lib/python3.6/site-packages/stagesepx/toolbox.py", line 49, in compare_ssim
    return origin_compare_ssim(pic1, pic2)
  File "/Users/xxxx/lib/python3.6/site-packages/skimage/metrics/_structural_similarity.py", line 89, in structural_similarity
    check_shape_equality(im1, im2)
  File "/Users/xxxx/lib/python3.6/site-packages/skimage/_shared/utils.py", line 156, in check_shape_equality
    if not im1.shape == im2.shape:
AttributeError: 'NoneType' object has no attribute 'shape'

```

**Comment by williamfzc** [comment]
需要视频复现

**Comment by wuchengyuan** [comment]
> 需要视频复现
链接：https://pan.baidu.com/s/1lQNmKVX17wcn-wkUMiPM2g 
提取码：nhmi

**Comment by williamfzc** [comment]
> > 需要视频复现
> > 链接：https://pan.baidu.com/s/1lQNmKVX17wcn-wkUMiPM2g
> > 提取码：nhmi

see https://github.com/williamfzc/stagesepx/issues/116
