### ISSUE TITLE
AssertionError: read frame failed

### ISSUE THREAD

**Issue by zangtian2** [williamfzc/stagesepx#111]
2020-04-02 22:59:27.320 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 494(23.68007777777778)
2020-04-02 22:59:27.476 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 504(25.3065)
2020-04-02 22:59:27.626 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 505(0.0)
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    main("SM-G9500_20200402220023.mp4")
  File "E:\code\python\PerfTool\simpleStagesepx.py", line 26, in main
    r.draw(classify_result)
  File "D:\software\tool\miniconda\lib\site-packages\stagesepx\reporter.py", line 246, in draw
    for i in new_each
  File "D:\software\tool\miniconda\lib\site-packages\stagesepx\reporter.py", line 246, in <listcomp>
    for i in new_each
  File "D:\software\tool\miniconda\lib\site-packages\stagesepx\classifier\base.py", line 49, in get_data
    return self.to_video_frame().data
  File "D:\software\tool\miniconda\lib\site-packages\stagesepx\classifier\base.py", line 44, in to_video_frame
    frame = toolbox.get_frame(cap, self.frame_id)
  File "D:\software\tool\miniconda\lib\site-packages\stagesepx\toolbox.py", line 116, in get_frame
    assert ret, f"read frame failed, frame id: {frame_id}"
AssertionError: read frame failed, frame id: 516

**Comment by williamfzc** [comment]
视频先用ffmpeg处理

```bash
ffmpeg -i YOUR_VIDEO.mp4 -r 60 output.mp4
```

**Comment by zangtian2** [comment]
好的，妥妥的。666
