### ISSUE TITLE
6个以上阶段的训练集如何配置

### ISSUE THREAD

**Issue by wanmich** [williamfzc/stagesepx#112]
目前项目中有一个阶段比较多的业务流程，视频分类下来有8个阶段（即0~7），使用dynamic/train_model.py训练时报错，提示只支持6个阶段（即[0, 6)），尝试对阶段数量进行精简，但报告中的分类结果与期望相差太大，若阶段数量过多，应如何进行配置，谢谢！

***报错如下：***
```
2020-04-10 16:32:24.828689: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at sparse_xent_op.cc:90 : Invalid argument: Received a label value of 7 which is outside the valid range of [0, 6).  Label values: 7 2 4 6 7 7 7 7 7 0 7 7 6 6 7 7 4 0 7 1 7 3 7 5 7 7 6 7 7 3 7 7
2020-04-10 16:32:24.828750: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Received a label value of 7 which is outside the valid range of [0, 6).  Label values: 7 2 4 6 7 7 7 7 7 0 7 7 6 6 7 7 4 0 7 1 7 3 7 5 7 7 6 7 7 3 7 7
	 [[{{node loss/activation_5_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
Traceback (most recent call last):
  File "train_model.py", line 13, in <module>
    cl.train(data_home)
  File "/usr/local/lib/python3.7/site-packages/stagesepx/classifier/keras.py", line 169, in train
    validation_steps=self.nb_validation_samples // self.batch_size,
  File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Received a label value of 7 which is outside the valid range of [0, 6).  Label values: 7 2 4 6 7 7 7 7 7 0 7 7 6 6 7 7 4 0 7 1 7 3 7 5 7 7 6 7 7 3 7 7
	 [[node loss/activation_5_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at /usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_1052]

Function call stack:
keras_scratch_graph
```

**Comment by williamfzc** [comment]
- 一开始设计的时候不希望开发者引入过多类型，所以将类别上限锁死了；
- 目前没有暴露原生的参数供修改，后面可能会考虑加入；
- 如果急着使用，可以自己继承 KerasClassifier 去改写这个函数，将最后的 Dense(6) 进行修改； https://github.com/williamfzc/stagesepx/blob/3451c67792a0b8ded001c072d56cdcaebb8dc719/stagesepx/classifier/keras.py#L96
- 不过使用至今我还没见过需要这么多类别的场景，阶段数量的精简通常效果还可以，可以分享一下吗？

**Comment by wanmich** [comment]
业务流程大致如下：
```
          点击应用图标              弹窗1   关闭弹窗1     欢迎页     滑动欢迎页    弹窗2    关闭弹窗2   首页
              ^                     ^                   ^                     ^                  ^ 
              |                     |                   |                     |                  |
              |---------logo1-------|-------logo2-------|--------.......------|------......------|

稳定阶段（个）： 2         1          1         1          1                     1                  2

              |                     |                   |                     |                  |
              v                     v                   v                     v                  v
              A                     B                   C                     D                  E
```

因logo1、logo2、弹窗1、弹窗2有一定相似度，尝试精简阶段（如A - E）及全阶段下调整参数（如cutter = VideoCutter(target_size=(1080, 1920)) 或/且 res = cutter.cut(video, block=8,)），结果总会出现部分误判（后面阶段提前出现或前面阶段出现在后），阻碍自动化统计，如：
（分割视频后，按默认参数可实现正确判断）

>Time Cost between stages
Calculate the time spent on stage changes.
stage from -3 to 0
range: 1 - 4 (0.0 - 1.219588888888889)
time cost: 1.219588888888889
stage from 0 to 5
range: 7 - 23 (1.285388888888889 - 1.5550666666666668)
time cost: 0.2696777777777779
stage from 5 to 5
range: 70 - 72 (6.493033333333334 - 6.524577777777778)
time cost: 0.03154444444444415
stage from 5 to 4
range: 36 - 41 (3.9547444444444446 - 4.047988888888889)
time cost: 0.09324444444444424
stage from 4 to 5
range: 63 - 69 (5.132966666666667 - 6.474855555555556)
time cost: 1.3418888888888887
stage from 5 to 6
range: 407 - 426 (14.804555555555556 - 15.12268888888889)
time cost: 0.3181333333333338
stage from 6 to 7
range: 467 - 480 (17.697922222222225 - 18.217822222222225)
time cost: 0.5198999999999998
stage from 7 to 8
range: 489 - 499 (18.38338888888889 - 18.752655555555556)
time cost: 0.36926666666666463
stage from 8 to 8
range: 525 - 527 (20.1402 - 20.174455555555557)
time cost: 0.03425555555555704
stage from 8 to 9
range: 510 - 520 (18.985511111111112 - 19.53653333333333)
time cost: 0.551022222222219
stage from 9 to 8
range: 522 - 524 (19.6373 - 20.107566666666667)
time cost: 0.4702666666666673
stage from 8 to 10
range: 527 - 537 (20.174455555555557 - 20.341544444444445)
time cost: 0.1670888888888875
stage from 10 to 11
range: 603 - 608 (23.15227777777778 - 23.256422222222223)
time cost: 0.1041444444444437
stage from 11 to 11
range: 616 - 619 (23.38698888888889 - 23.43928888888889)
time cost: 0.0522999999999989
stage from 2 to 2
range: 638 - 640 (23.820977777777777 - 24.364)
time cost: 0.5430222222222234
stage from 2 to 3
range: 641 - 643 (24.390900000000002 - 24.808722222222222)
time cost: 0.4178222222222203
stage from 3 to 3
range: 757 - 760 (27.268244444444445 - 27.317844444444447)
time cost: 0.04960000000000164

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC

方便的话视频私发一下？这样我能得到的信息很少，也比较难定位问题呢

**Comment by wanmich** [comment]
基于业务流程、实际需求，尝试不同的阶段分类方法，实现了本业务对应视频的自动化准确判断/预测。
感谢 @williamfzc 的指导和建义。

**总结：**
对业务流程视频较长、stable/unstable阶段较多且部分阶段相似度较高，若碰到预测不准确的情况，建议回到原点，从实际需求出发，重新思考，灵活对训练集的阶段进行划分/切割，多尝试几次再看看结果。若因为部分阶段相似度过高造成判断结果不稳定，不能实现自动化耗时计算，可考虑人工统计或分段录制视频再实现自动化。

**Comment by williamfzc** [comment]
在 0.17.0 之后，dense 可以直接设置，但依旧保留原来的建议。

```python
# 可以修改为合适的上限
KerasClassifier.MODEL_DENSE = 6
```

如果需要更高程度的定制，可以自己继承 KerasClassifier 进行随意修改。
