### ISSUE TITLE
iphone X 自带的录屏工具录制视频进行分析，在生成报告过程中报错！

### ISSUE THREAD

**Issue by Pactortester** [williamfzc/stagesepx#135]
![image](https://user-images.githubusercontent.com/29191106/91799383-8375c780-ec59-11ea-9446-c66a79334b2c.png)
`2020-09-01 13:45:50.966 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 134(2.263270777479893)
2020-09-01 13:45:51.274 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 138(2.3308310991957106)
2020-09-01 13:45:51.588 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 139(2.347721179624665)
2020-09-01 13:45:51.905 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 140(2.3646112600536195)
2020-09-01 13:45:52.297 | DEBUG    | stagesepx.toolbox:video_jump:43 - previous pointer: 130(2.195710455764075)
20200825_ios_4G.mp4
Traceback (most recent call last):
  File "run_ios.py", line 56, in <module>
    r.draw(report_path=r'html_ios\index.html', classifier_result=classify_result)
  File "D:\python\lib\site-packages\stagesepx\reporter.py", line 231, in draw
    middle.get_data(),
  File "D:\python\lib\site-packages\stagesepx\classifier\base.py", line 49, in get_data
    return self.to_video_frame().data
  File "D:\python\lib\site-packages\stagesepx\classifier\base.py", line 44, in to_video_frame
    frame = toolbox.get_frame(cap, self.frame_id)
  File "D:\python\lib\site-packages\stagesepx\toolbox.py", line 116, in get_frame
    assert ret, f"read frame failed, frame id: {frame_id}"
AssertionError: read frame failed, frame id: 226`

**Comment by williamfzc** [comment]
参考 #111

**Comment by Pactortester** [comment]
好的，非常感谢！！！
