### ISSUE TITLE
RuntimeError: frame 1 not found in video

### ISSUE THREAD

**Issue by wenhuichen** [williamfzc/stagesepx#156]
1、ffmpeg -y -i 1619491781494030.mp4 -r 60 video-ffmpeg.mp4
2、stagesepx analyse  report.html

报错，视频见附件：
2021-04-27 11:48:42.820 | DEBUG    | stagesepx.cutter.cut_result:get_range:172 - stable start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/stagesepx", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stagesepx/cli.py", line 24, in main
    fire.Fire(TerminalCli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stagesepx/api.py", line 268, in analyse
    offset=offset,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 180, in get_range
    first_stable_range_end_id
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 32, in get_target_range_by_id
    raise RuntimeError(f"frame {frame_id} not found in video")
RuntimeError: frame 1 not found in video

https://user-images.githubusercontent.com/6110769/116183302-31d1fe00-a750-11eb-90f7-3732c76ea12a.mp4

**Comment by williamfzc** [comment]
2、

```shell
stagesepx analyse video-ffmpeg.mp4 report.html
```
