### ISSUE TITLE
RuntimeError: frame 1 not found in video  FFmpeg处理之后还是报错

### ISSUE THREAD

**Issue by lxlin** [williamfzc/stagesepx#159]
同一个手机自带录屏软件录制，就一个视频FFmpeg之后能成功

基本操作如下：

DeviceExplorer %  ./ffmpeg -i 阻塞2.mp4 -r 60 block2.mp4 
ffmpeg version N-102799-g49e3a8165c-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  2.100 / 59.  2.100
  libavformat    59.  3.101 / 59.  3.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '阻塞2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-07-01T02:35:51.000000Z
    com.android.version: 10
  Duration: 00:00:06.91, start: 0.000000, bitrate: 7292 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, unknown/bt470bg/unknown), 720x1520, 7159 kb/s, SAR 1:1 DAR 9:19, 39.37 fps, 90k tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2021-07-01T02:35:51.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-07-01T02:35:51.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
File 'block2.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x7f992740ea40] using SAR=1/1
[libx264 @ 0x7f992740ea40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f992740ea40] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x7f992740ea40] 264 - core 164 r3065 ae03d92 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'block2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 10
    encoder         : Lavf59.3.101
  Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, unknown/bt470bg/unknown, progressive), 720x1520 [SAR 1:1 DAR 9:19], q=2-31, 60 fps, 15360 tbn (default)
    Metadata:
      creation_time   : 2021-07-01T02:35:51.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.2.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      creation_time   : 2021-07-01T02:35:51.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.2.100 aac
frame=   53 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A dup=1 droframe=  122 fps=0.0 q=31.0 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/frame=  181 fps=137 q=31.0 size=     512kB time=00:00:03.00 bitrate=1394.5kbits/frame=  306 fps=168 q=31.0 size=     768kB time=00:00:06.01 bitrate=1045.9kbits/frame=  414 fps=182 q=-1.0 Lsize=     876kB time=00:00:06.85 bitrate=1048.1kbits/s dup=142 drop=0 speed=3.01x    
video:863kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.383603%
[libx264 @ 0x7f992740ea40] frame I:2     Avg QP:22.63  size: 35354
[libx264 @ 0x7f992740ea40] frame P:129   Avg QP:19.34  size:  4869
[libx264 @ 0x7f992740ea40] frame B:283   Avg QP:18.59  size:   652
[libx264 @ 0x7f992740ea40] consecutive B-frames:  5.3%  8.2%  7.2% 79.2%
[libx264 @ 0x7f992740ea40] mb I  I16..4: 27.5% 46.2% 26.2%
[libx264 @ 0x7f992740ea40] mb P  I16..4:  3.5%  6.6%  1.0%  P16..4: 10.1%  2.0%  0.9%  0.0%  0.0%    skip:75.8%
[libx264 @ 0x7f992740ea40] mb B  I16..4:  0.4%  0.3%  0.0%  B16..8:  5.9%  0.4%  0.0%  direct: 0.4%  skip:92.6%  L0:51.4% L1:45.7% BI: 2.9%
[libx264 @ 0x7f992740ea40] 8x8 transform intra:55.9% inter:78.0%
[libx264 @ 0x7f992740ea40] coded y,uvDC,uvAC intra: 25.5% 16.4% 2.8% inter: 1.4% 1.8% 0.1%
[libx264 @ 0x7f992740ea40] i16 v,h,dc,p: 31% 54%  7%  8%
[libx264 @ 0x7f992740ea40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 30% 27%  3%  1%  4%  1%  2%  4%
[libx264 @ 0x7f992740ea40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 40% 12%  3%  3%  5%  2%  3%  3%
[libx264 @ 0x7f992740ea40] i8c dc,h,v,p: 68% 23%  9%  1%
[libx264 @ 0x7f992740ea40] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x7f992740ea40] ref P L0: 73.0%  7.8% 11.7%  7.4%
[libx264 @ 0x7f992740ea40] ref B L0: 82.0% 15.2%  2.8%
[libx264 @ 0x7f992740ea40] ref B L1: 97.7%  2.3%
[libx264 @ 0x7f992740ea40] kb/s:1024.03
[aac @ 0x7f9927412500] Qavg: 65447.914

// 生成HTML
 DeviceExplorer % stagesepx analyse block2.mp4 reportblock1.html
.
.
.
  File "/usr/local/lib/python3.8/site-packages/stagesepx/cutter/cut_result.py", line 32, in get_target_range_by_id
    raise RuntimeError(f"frame {frame_id} not found in video")
RuntimeError: frame 1 not found in video

**Comment by williamfzc** [comment]
可以的话发一下视频

**Comment by lxlin** [comment]
> 可以的话发一下视频

涉及业务不方便公开，加你QQ了

**Comment by ssfanli** [comment]
目前我这也遇到了，没用ffmpge，报：`AttributeError: 'NoneType' object has no attribute 'frame_id'`，用它规整到60FPS之后的视频，报`RuntimeError: frame 1 not found in video FFmpeg`

**Comment by williamfzc** [comment]
> 目前我这也遇到了，没用ffmpge，报：`AttributeError: 'NoneType' object has no attribute 'frame_id'`，用它规整到60FPS之后的视频，报`RuntimeError: frame 1 not found in video FFmpeg`

- 没用的话本来就很可能会报错
- 这里可能是你的命令行写得有问题，video名字是FFmpeg？

**Comment by ssfanli** [comment]
> > 目前我这也遇到了，没用ffmpge，报：`AttributeError: 'NoneType' object has no attribute 'frame_id'`，用它规整到60FPS之后的视频，报`RuntimeError: frame 1 not found in video FFmpeg`
> 
> * 没用的话本来就很可能会报错
> * 这里可能是你的命令行写得有问题，video名字是FFmpeg？

抱歉，我贴错了，下面是正确的堆栈
```
2021-07-26 10:16:37.390 | DEBUG    | stagesepx.cutter.cut_result:get_range:172 - stable start
Traceback (most recent call last):
  File "/usr/local/bin/stagesepx", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/stagesepx/cli.py", line 24, in main
    fire.Fire(TerminalCli)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/stagesepx/api.py", line 268, in analyse
    offset=offset,
  File "/usr/local/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 180, in get_range
    first_stable_range_end_id
  File "/usr/local/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 32, in get_target_range_by_id
    raise RuntimeError(f"frame {frame_id} not found in video")
RuntimeError: frame 1 not found in video
```

**Comment by ssfanli** [comment]
> > > 目前我这也遇到了，没用ffmpge，报：`AttributeError: 'NoneType' object has no attribute 'frame_id'`，用它规整到60FPS之后的视频，报`RuntimeError: frame 1 not found in video FFmpeg`
> > 
> > 
> > 
> > * 没用的话本来就很可能会报错
> > * 这里可能是你的命令行写得有问题，video名字是FFmpeg？
> 
> 抱歉，我贴错了，下面是正确的堆栈
> 
> ```
> 2021-07-26 10:16:37.390 | DEBUG    | stagesepx.cutter.cut_result:get_range:172 - stable start
> Traceback (most recent call last):
>   File "/usr/local/bin/stagesepx", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/stagesepx/cli.py", line 24, in main
>     fire.Fire(TerminalCli)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
>     target=component.__name__)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/stagesepx/api.py", line 268, in analyse
>     offset=offset,
>   File "/usr/local/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 180, in get_range
>     first_stable_range_end_id
>   File "/usr/local/lib/python3.7/site-packages/stagesepx/cutter/cut_result.py", line 32, in get_target_range_by_id
>     raise RuntimeError(f"frame {frame_id} not found in video")
> RuntimeError: frame 1 not found in video
> ```


这两个视频，一个用ffmpeg处理了下(xxx_60fps.mp4)，一个没有处理，但是解析的时候依然都报`RuntimeError: frame 1 not found in video`

https://user-images.githubusercontent.com/53210634/131473655-2d904176-5bca-4960-94ef-54af6e17a2d3.mp4


https://user-images.githubusercontent.com/53210634/131473749-825e6018-b7d0-40c4-9645-9dbf200c238a.mp4

**Comment by williamfzc** [comment]
"opencv-python>=4.1.2.30",
"opencv-contrib-python>=4.1.2.30",

看下这两个版本

**Comment by ssfanli** [comment]
![image](https://user-images.githubusercontent.com/53210634/131475134-7967b9c1-420d-4063-b648-624c69bff0b7.png)

**Comment by williamfzc** [comment]
之前有成功过吗，还是所有的视频都不行？work_with_stagesepx 里的视频可以吗

**Comment by ssfanli** [comment]
> 之前有成功过吗，还是所有的视频都不行？work_with_stagesepx 里的视频可以吗

一组视频中有的可以，有的就抛出异常
另外，我给你qq留言了～

**Comment by williamfzc** [comment]
那两个视频都跑了，都没问题

opencv-contrib-python  4.2.0.32      
opencv-python          4.2.0.32

**Comment by williamfzc** [comment]
那两个视频都跑了，都没问题

opencv-contrib-python  4.2.0.32      
opencv-python          4.2.0.32 

如果还有问题可以试试用脚本而不是命令行

**Comment by ssfanli** [comment]
好的，我用脚本试试

**Comment by linyajun558** [comment]
我也碰到了这个问题，我把fps提升到90之后ok了，我怀疑是我的视频本身帧率高于60，我设置成60之后低于原视频的帧率导致的，我提高fps之后就正常了
