### ISSUE TITLE
分类的类型超过6个遇到assert异常

### ISSUE THREAD

**Issue by mayan90** [williamfzc/stagesepx#170]
2022-03-09 14:46:07.978 | DEBUG    | stagesepx.classifier.base:__init__:346 - no compress rate or target size received. set compress rate to 0.2
2022-03-09 14:46:07.978 | DEBUG    | stagesepx.classifier.base:__init__:353 - compress rate: 0.2
2022-03-09 14:46:07.978 | DEBUG    | stagesepx.classifier.base:__init__:354 - target size: None
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.hook:__init__:13 - start initialing: CompressHook ...
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.hook:__init__:80 - compress rate: 0.2
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.hook:__init__:81 - target size: None
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.hook:__init__:13 - start initialing: GreyHook ...
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.base:add_hook:375 - add hook: CompressHook
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.base:add_hook:375 - add hook: GreyHook
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:50 - score threshold: 0.0
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:51 - data size: (200, 200)
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:52 - nb train samples: 64
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:53 - nb validation samples: 64
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:54 - epochs: 10
2022-03-09 14:46:07.979 | DEBUG    | stagesepx.classifier.keras:__init__:55 - batch size: 4
Traceback (most recent call last):
  File "工作记录/KbPerformanceTest/testa.py", line 10, in <module>
    cl.train('Desktop/monkey/table_frame')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/stagesepx/classifier/keras.py", line 157, in train
    _data_verify(data_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/stagesepx/classifier/keras.py", line 152, in _data_verify
    assert number_of_dir <= 6, (
AssertionError: dataset has 12 classes (more than 6), please see https://github.com/williamfzc/stagesepx/issues/112 

Process finished with exit code 1

**Comment by williamfzc** [comment]
强烈建议还是不要超出6个类型，我觉得场景过度复杂化了，几乎所有场景都可以在6个类内完成，大部分的类都可以合并。

如果一定要用那么多类型：
- 你这里有12个classes那自然要修改为12
- assert可以自行去掉

**Comment by mayan90** [comment]
嗨改为12了 还是报错的。还有哪里需要修改

**Comment by williamfzc** [comment]
> 嗨改为12了 还是报错的。还有哪里需要修改

- 分不到6个类型的理由是啥呢
- 发堆栈

**Comment by mayan90** [comment]
/usr/local/bin/python3.9 //Desktop/工作记录/KbPerformanceTest/testa.py
2022-03-09 15:25:00.140 | DEBUG    | stagesepx.classifier.base:__init__:346 - no compress rate or target size received. set compress rate to 0.2
2022-03-09 15:25:00.140 | DEBUG    | stagesepx.classifier.base:__init__:353 - compress rate: 0.2
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.classifier.base:__init__:354 - target size: None
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.hook:__init__:13 - start initialing: CompressHook ...
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.hook:__init__:80 - compress rate: 0.2
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.hook:__init__:81 - target size: None
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.hook:__init__:13 - start initialing: GreyHook ...
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.classifier.base:add_hook:375 - add hook: CompressHook
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.classifier.base:add_hook:375 - add hook: GreyHook
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.classifier.keras:__init__:50 - score threshold: 0.0
2022-03-09 15:25:00.141 | DEBUG    | stagesepx.classifier.keras:__init__:51 - data size: (200, 200)
2022-03-09 15:25:00.142 | DEBUG    | stagesepx.classifier.keras:__init__:52 - nb train samples: 64
2022-03-09 15:25:00.142 | DEBUG    | stagesepx.classifier.keras:__init__:53 - nb validation samples: 64
2022-03-09 15:25:00.142 | DEBUG    | stagesepx.classifier.keras:__init__:54 - epochs: 10
2022-03-09 15:25:00.142 | DEBUG    | stagesepx.classifier.keras:__init__:55 - batch size: 4
Traceback (most recent call last):
  File "Desktop/工作记录/KbPerformanceTest/testa.py", line 10, in <module>
    cl.train('Desktop/monkey/table_frame')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/stagesepx/classifier/keras.py", line 157, in train
    _data_verify(data_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/stagesepx/classifier/keras.py", line 152, in _data_verify
    assert number_of_dir <= 6, (
AssertionError: dataset has 12 classes (more than 6), please see https://github.com/williamfzc/stagesepx/issues/112

**Comment by mayan90** [comment]
生成的就是12的区间，不是6 也没有报错。

**Comment by williamfzc** [comment]
如果不是持久性的模型可以不用Keras，用默认的svm就可以了
可以贴下脚本

**Comment by mayan90** [comment]
from stagesepx.cutter import VideoCutter
from stagesepx.video import VideoObject

# 将视频切分成帧
file_name = '/Users/xm210407/Desktop/monkey/视频/2022_03_08_11_39_IMG_0730.MOV'
video = VideoObject(file_name, pre_load=True)
# 新建帧，计算视频总共有多少帧，每帧多少ms
video.load_frames()
# 压缩视频
cutter = VideoCutter()
# 计算每一帧视频的每一个block的ssim和psnr。
res = cutter.cut(video, block=6)
# 计算出判断A帧到B帧之间是稳定还是不稳定
stable, unstable = res.get_range(threshold=0.96)
# 把分好类的稳定阶段的图片存本地
res.pick_and_save(stable, 20, to_dir='/Users/xm210407/Desktop/monkey/table_frame', meaningful_name=True)

**Comment by mayan90** [comment]
# 训练模型文件
cl = KerasClassifier(
# 训练轮数
epochs=10
)
cl.train('/Users/xm210407/Desktop/monkey/table_frame')
cl.save_model('/Users/xm210407/Desktop/monkey/table_model/model.h5', overwrite=True)

**Comment by williamfzc** [comment]
https://blog.csdn.net/wsc106/article/details/107351675
参考下能不能压缩类型，12个肯定是过多的也不必要的，看你的场景只需要5个。
