### ISSUE TITLE
RuntimeError: frame 1 not found in video

### ISSUE THREAD

**Issue by longzhendd** [williamfzc/stagesepx#177]
2022-05-17 11:38:15.287 | DEBUG    | stagesepx.cutter.cut_result:get_range:174 - stable start
Traceback (most recent call last):
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\Scripts\stagesepx.exe\__main__.py", line 7, in <module>
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stagesepx\cli.py", line 24, in main
    fire.Fire(TerminalCli)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fire\core.py", line 138, in Fire    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stagesepx\api.py", line 269, in analyse
    offset=offset,
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stagesepx\cutter\cut_result.py", line 182, in get_range
    first_stable_range_end_id
  File "C:\Users\v_zhenlong\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stagesepx\cutter\cut_result.py", line 34, in get_target_range_by_id
    raise RuntimeError(f"frame {frame_id} not found in video")
RuntimeError: frame 1 not found in video

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx/issues/159
