### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'frame_id'

### ISSUE THREAD

**Issue by milu534334864** [williamfzc/stagesepx#179]
按照介绍想快速使用体验一下，出现报错，报错信息如下
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\stagesepx-script.py", line 11, in <module>
    load_entry_point('stagesepx==0.16.2', 'console_scripts', 'stagesepx')()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\cli.py", line 24, in main
    fire.Fire(TerminalCli)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\api.py", line 265, in analyse
    res = cutter.cut(video)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\cutter\cutter.py", line 242, in cut
    range_list = self._convert_video_into_range_list(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\cutter\cutter.py", line 164, in _convert_video_into_range_list
    frame_list = [self._apply_hook(each) for each in frame_list]
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\cutter\cutter.py", line 164, in <listcomp>
    frame_list = [self._apply_hook(each) for each in frame_list]
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\cutter\cutter.py", line 66, in _apply_hook
    frame = each_hook.do(frame, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\hook.py", line 84, in do
    super().do(frame, *_, **__)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\stagesepx\hook.py", line 21, in do
    frame_id = frame.frame_id
AttributeError: 'NoneType' object has no attribute 'frame_id'

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx/issues/116#issuecomment-620468139
参考这里解决
