### ISSUE TITLE
from ._cascade import Cascade ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by Wangdenan** [williamfzc/stagesepx#182]
windows 运行项目报错
Traceback (most recent call last):
  File "D:/Code/stagesepx/stagesepx_with_keras-master/demo/demo.py", line 1, in <module>
    from stagesepx.classifier import SVMClassifier
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\classifier\__init__.py", line 1, in <module>
    from stagesepx.classifier.base import SingleClassifierResult, ClassifierResult
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\classifier\base.py", line 12, in <module>
    from stagesepx.cutter import VideoCutRange
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\cutter\__init__.py", line 1, in <module>
    from .cutter import VideoCutter
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\cutter\cutter.py", line 6, in <module>
    from stagesepx import toolbox
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\toolbox.py", line 14, in <module>
    from skimage.feature import hog, local_binary_pattern
  File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\skimage\feature\__init__.py", line 4, in <module>
    from ._cascade import Cascade
ImportError: DLL load failed: 找不到指定的模块。

**Comment by williamfzc** [comment]
> windows 运行项目报错
> 
> Traceback (most recent call last):
> 
>   File "D:/Code/stagesepx/stagesepx_with_keras-master/demo/demo.py", line 1, in <module>
> 
>     from stagesepx.classifier import SVMClassifier
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\classifier\__init__.py", line 1, in <module>
> 
>     from stagesepx.classifier.base import SingleClassifierResult, ClassifierResult
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\classifier\base.py", line 12, in <module>
> 
>     from stagesepx.cutter import VideoCutRange
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\cutter\__init__.py", line 1, in <module>
> 
>     from .cutter import VideoCutter
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\cutter\cutter.py", line 6, in <module>
> 
>     from stagesepx import toolbox
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\stagesepx\toolbox.py", line 14, in <module>
> 
>     from skimage.feature import hog, local_binary_pattern
> 
>   File "C:\Users\wangdenan1\Envs\stagsepx\lib\site-packages\skimage\feature\__init__.py", line 4, in <module>
> 
>     from ._cascade import Cascade
> 
> ImportError: DLL load failed: 找不到指定的模块。
> 
> 

skimage环境问题，google下哈

**Comment by as45045781** [comment]
解决方法：
pip uninstall scikit-image
pip install scikit-image==0.18.0rc0
