### ISSUE TITLE
compare_videos.py 对比2个视频相似度时，脚本报错了

### ISSUE THREAD

**Issue by lycfr** [williamfzc/stagesepx#20]
`Traceback (most recent call last):
  File "D:/pythonworkpace/stagesepx/example/compare_videos.py", line 13, in <module>
    stable, _ = res.get_range(limit=3)
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 197, in get_range
    unstable_range_list = self.get_unstable_range(limit, **kwargs)
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 168, in get_unstable_range
    if change_range_list[-1].start > merged_change_range_list[-1].end:
IndexError: list index out of range`
拉去的是最新代码

**Comment by lycfr** [comment]
你好，我运行cut也会报错，目前就一个cut_and_classify.py可以运行通过，我是哪个引用的依赖库和你不一样的吗？
`"D:\Program Files\Python\python.exe" D:/pythonworkpace/stagesepx/example/cut.py
D:\Program Files\Python\lib\site-packages\findit\engine\ocr.py:11: UserWarning: findtext should be installed if you want to use OCR engine
  warnings.warn('findtext should be installed if you want to use OCR engine')
2019-08-06 10:43:39.071 | INFO     | stagesepx.cutter:cut:450 - start cutting: ../test.mp4
2019-08-06 10:43:39.090 | DEBUG    | stagesepx.cutter:convert_video_into_ssim_list:383 - total frame count: 258, size: (480, 864)
2019-08-06 10:43:39.105 | DEBUG    | stagesepx.cutter:convert_video_into_ssim_list:404 - split function: vsplit
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\numpy\lib\shape_base.py", line 843, in split
    len(indices_or_sections)
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pythonworkpace/stagesepx/example/cut.py", line 18, in <module>
    compress_rate=0.2
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 456, in cut
    ssim_list = self.convert_video_into_ssim_list(video_path, **kwargs)
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 409, in convert_video_into_ssim_list
    start_part_list = self.pic_split(start, block)
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 370, in pic_split
    for i in range(column)
  File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 370, in <listcomp>
    for i in range(column)
  File "D:\Program Files\Python\lib\site-packages\numpy\lib\shape_base.py", line 972, in vsplit
    return split(ary, indices_or_sections, 0)
  File "D:\Program Files\Python\lib\site-packages\numpy\lib\shape_base.py", line 849, in split
    'array split does not result in an equal division')
ValueError: array split does not result in an equal division

Process finished with exit code 1
`

**Comment by williamfzc** [comment]
第二个问题我早上提了一版代码，你更新下应该可以解决；
第一个我再看看哈

**Comment by lycfr** [comment]
请问一下，我能把这个切割过程的图片保存到本地？需要怎么保存？

**Comment by williamfzc** [comment]
> 请问一下，我能把这个切割过程的图片保存到本地？需要怎么保存？

https://github.com/williamfzc/stagesepx/blob/master/example/cut.py#L49

这个就是保存到本地

**Comment by williamfzc** [comment]
> `Traceback (most recent call last): File "D:/pythonworkpace/stagesepx/example/compare_videos.py", line 13, in <module> stable, _ = res.get_range(limit=3) File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 197, in get_range unstable_range_list = self.get_unstable_range(limit, **kwargs) File "D:\pythonworkpace\stagesepx\stagesepx\cutter.py", line 168, in get_unstable_range if change_range_list[-1].start > merged_change_range_list[-1].end: IndexError: list index out of range`
> 拉去的是最新代码

没视频可能比较难分析，可以 把视频打个包传上来 或者 留个别的联系方式 或者 发到我邮箱：fengzc@vip.qq.com ~
